# Generated by Django 4.0.3 on 2022-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
                ("date", models.DateField()),
            ],
        ),
    ]
