# Generated by Django 4.0.3 on 2022-03-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
