# Generated by Django 4.0.3 on 2022-04-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="expenses.expense",
            ),
        ),
    ]
