# Generated by Django 4.0.3 on 2022-05-16 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("teaser", models.TextField()),
                ("content", models.TextField()),
            ],
        ),
    ]
