# Generated by Django 4.0.3 on 2022-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog.tag"
            ),
        ),
    ]
